import = [
    "~/.config/alacritty/alacritty-theme/themes/ayu_dark.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 5
opacity=0.95
blur=true
startup_mode='Maximized'


[font]
normal.family = "JetBrainsMono NF"

#regular
size = 15

#for video
# size = 35.0
