general.import = [
    "~/.config/alacritty/alacritty-theme/themes/one_dark.toml"
]
[ env ]
# TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4
# opacity=0.90
blur=true
startup_mode='Maximized'


[font]
# normal.family = "JetBrainsMono NF"
normal.family = "JetBrainsMono NF SemiBold"
offset.y = 2

#regular
size = 11

#for video
# size = 35.0
