import = [
    "~/dotfiles/.config/alacritty/alacritty-theme/themes/ayu_dark.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 2
opacity=0.90
blur=true
startup_mode='Maximized'


[font]
normal.family = "JetBrainsMono NF"

#regular
size = 14

#for video
# size = 35.0
