reload("user.options")
reload("user.keymapings")
reload("user.plugins_config.lspconfig")
reload("user.plugins_config.telescope")
reload("user.plugins_config.nvim-cmp")
reload("user.plugins_config.nvimtree")
reload("user.plugins_config.bufferline")
reload("user.plugins")
